
export interface BrandInfo {
  full: string;
  name: string;
  tld: string;
  domain: string;
  short: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
  alternateNames: string[];
}

const BRANDS: Record<string, BrandInfo> = {
  'netcheck.site': {
    full: 'NetCheck.site',
    name: 'NetCheck',
    tld: '.site',
    domain: 'netcheck.site',
    short: 'NetCheck',
    seoTitle: 'NetCheck.site - Net Check & Speed Check | Internet Speed Test, PTCL, WiFi Analyzer',
    seoDescription: 'NetCheck.site - Fast Net Check, Speed Check, Internet Speed Test, PTCL Speed Test, Fiberlink Speed Test, WiFi Analyzer, My IP Country Map, What is My IP, Ping Test, Speed Test Internet, Blog. Search net check, netcheck, netcheck.site, speed check, wifi analyzer, my ip country map - always top!',
    keywords: [
      'net check',
      'netcheck',
      'netcheck.site',
      'net check site',
      'netcheck site',
      'net check .site',
      'netcheck dot site',
      'net check dot site',
      'net check online',
      'netcheck online',
      'net speed test',
      'net speed check',
      'check net speed',
      'internet speed test',
      'internet speed check',
      'speed check',
      'speedcheck',
      'speed test',
      'speed test internet',
      'internet speed test online',
      'fast internet speed test',
      'check internet speed',
      'test my internet speed',
      'speed check online',
      'speedcheck online',
      'wifi analyzer',
      'wifi map',
      'wifi signal map',
      'wifi signal',
      'wifi speed test',
      'wifi checker',
      'my ip',
      'what is my ip',
      'my ip address',
      'my ip country map',
      'ip checker',
      'ip check',
      'what is my ip address',
      'my public ip',
      'ping test',
      'ping checker',
      'test ping',
      'check ping',
      'ping speed test',
      'ptcl speed test',
      'ptcl internet speed test',
      'ptcl speed check',
      'fiberlink speed test',
      'fiberlink internet speed test',
      'nayatel speed test',
      'stormfiber speed test',
      'transworld speed test',
      'speed test ptcl',
      'internet speed test ptcl',
      'speedcheck blog',
      'speed check blog',
      'netcheck blog',
      'net check blog',
      'blog speed test',
      'speed guides',
      'internet speed blog',
      'wifi analyzer blog',
      'ip checker blog',
      'speed test by ookla alternative',
      'fast.com alternative',
      'speedtest.net alternative',
      'speed check .org alternative',
      'internet speed test by speedcheck',
      'fast speed check',
      'accurate speed test',
      'free speed test',
      'online speed test',
      'broadband speed test',
      'fiber speed test',
      '5g speed test',
      'gaming ping test',
      'wifi speed analyzer',
      'my ip location',
      'ip location map',
      'internet tools',
      'net tools',
      'network tools',
      'check my net',
      'test my net',
      'net check tool'
    ],
    alternateNames: [
      'Net Check',
      'NetCheck',
      'NetCheck.site',
      'Net Check Site',
      'Net Check dot site',
      'Net Speed Test',
      'Net Speed Check',
      'Internet Speed Test',
      'Speed Check',
      'Speed Test',
      'PTCL Speed Test',
      'WiFi Analyzer',
      'My IP Country Map',
      'Speed Test Internet',
      'Fiberlink Speed Test',
      'What is My IP',
      'Ping Test',
      'Fast Internet Speed Test',
      'NetCheck Blog',
      'Net Check Blog'
    ]
  },
  'speedcheck.online': {
    full: 'SpeedCheck.online',
    name: 'SpeedCheck',
    tld: '.online',
    domain: 'speedcheck.online',
    short: 'SpeedCheck',
    seoTitle: 'SpeedCheck.online - Speed Check Online | Fast Internet Speed Test, Blog & Tools',
    seoDescription: 'SpeedCheck.online - #1 Speed Check Online, Fast Internet Speed Test, Blog - Speed Guides & Tips, WiFi Analyzer, My IP Country Map, PTCL Speed Test, Fiberlink Speed Test, What is My IP, Ping Test, Speed Test Internet. Search speed check, speedcheck, speedcheck.online, speedcheck blog, wifi analyzer - top result!',
    keywords: [
      'speed check',
      'speedcheck',
      'speedcheck.online',
      'speed check online',
      'speedcheck online',
      'speed check .online',
      'speedcheck dot online',
      'speed check dot online',
      'speed check blog',
      'speedcheck blog',
      'speedcheck online blog',
      'speed check online blog',
      'fast internet speed test',
      'internet speed test',
      'internet speed check',
      'speed test',
      'speed test internet',
      'internet speed test online',
      'check internet speed',
      'test my internet speed',
      'fast speed test',
      'accurate speed test',
      'free speed test',
      'online speed test',
      'net check',
      'netcheck',
      'netcheck.site',
      'net speed test',
      'check net speed',
      'wifi analyzer',
      'wifi map',
      'wifi signal map',
      'wifi signal',
      'wifi speed test',
      'wifi checker',
      'wifi analyzer blog',
      'my ip',
      'what is my ip',
      'my ip address',
      'my ip country map',
      'ip checker',
      'ip check',
      'my public ip',
      'what is my ip address',
      'ip location map',
      'ping test',
      'ping checker',
      'test ping',
      'check ping',
      'gaming ping test',
      'ptcl speed test',
      'ptcl internet speed test',
      'fiberlink speed test',
      'fiberlink internet speed test',
      'nayatel speed test',
      'speed test ptcl',
      'broadband speed test',
      'fiber speed test',
      '5g speed test',
      'blog speed test',
      'speed guides',
      'internet speed blog',
      'speed test tips',
      'how to check internet speed',
      'how to test wifi speed',
      'internet speed test by speedcheck',
      'fast.com alternative',
      'speedtest.net alternative',
      'speed check org',
      'speedcheck dev',
      'speed check .org alternative',
      'test my net',
      'check my internet',
      'internet tools',
      'speed testing tools',
      'network speed test',
      'broadband speed checker',
      'wifi speed checker',
      'my internet speed',
      'check my speed',
      'speedcheck online tools'
    ],
    alternateNames: [
      'Speed Check',
      'SpeedCheck',
      'SpeedCheck.online',
      'Speed Check Online',
      'Speed Check dot online',
      'SpeedCheck dot online',
      'Speed Check Blog',
      'SpeedCheck Blog',
      'Fast Internet Speed Test',
      'Internet Speed Test',
      'Speed Test',
      'WiFi Analyzer',
      'My IP Country Map',
      'PTCL Speed Test',
      'Fiberlink Speed Test',
      'What is My IP',
      'Speed Test Internet',
      'Internet Speed Test by SpeedCheck',
      'Fast Speed Check',
      'Speed Guides'
    ]
  }
};

export function getBrand(host?: string | null): BrandInfo {
  if (!host) return BRANDS['netcheck.site'];
  const clean = host.toLowerCase().replace(/^www\./, '').split(':')[0];
  if (clean.includes('speedcheck.online')) return BRANDS['speedcheck.online'];
  if (clean.includes('netcheck.site')) return BRANDS['netcheck.site'];
  if (clean.includes('localhost') || clean.includes('vercel.app')) return BRANDS['netcheck.site'];
  return BRANDS['netcheck.site'];
}
